### ISSUE TITLE
entering the Log context interface may feel it with invalid query

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/quickwit-datasource#121]
when viewing context around a line, we get the following interface:
![image](https://github.com/quickwit-oss/quickwit-datasource/assets/35889323/5d05f64c-67d3-47a7-9615-9ab3bd74a1d5)
As shown on the picture, the query is prefilled, but variables aren't substituted, resulting in an invalid query. It would be handy to perform the substitution when opening the interface

**Comment by ddelemeny** [comment]
Thanks! The issue looks like a duplicate of #77 

The query itself is OK and variable interpolation will be handled normally (the datasource API method for interpolation is called during a query call). This _should_ display results.

The gist of the issue is that  parser used for linting currently doesn't handle Grafana's query templating language, which leads to the displayed error state. I have ongoing work to fix that, but parsing mixed languages isn't quite straightforward.

**Comment by trinity-1686a** [comment]
maybe it would work, though I can't check, the `Run query` button is actually disabled for invalid queries

**Comment by ddelemeny** [comment]
Oooh ! Yup, definitely overlooked this detaili. Will fix !
