### ISSUE TITLE
Query variable sometimes shows 'None'

### ISSUE THREAD

**Issue by maxnovawind** [quickwit-oss/quickwit-datasource#55]
**Context:**

It seems that variables are sometimes lost when refreshing (F5) a dashboard with predefined query variables. 

This is my settings in grafana:

<img width="480" alt="Screenshot 2024-02-02 at 02 37 32" src="https://github.com/quickwit-oss/quickwit-datasource/assets/28343541/4ace3fb9-274c-4750-986f-de0ae958e413">

By checking the browser inspector, it appears to be related to a call with `_elastic/_msearch`:

   <img width="1404" alt="Screenshot 2024-02-02 at 02 17 37" src="https://github.com/quickwit-oss/quickwit-datasource/assets/28343541/946fdc7b-7196-48df-9c5c-1bf6f982f963">

   `{"size":0,"query":{"bool":{"filter":[{"range":{"":{"gte":"1706814729878","lte":"1706836329878"}}}]}},"aggs":{"1":{"terms":{"field":"attributes.environment","size":500,"order":{"_key":"asc"}}}}}`
  

As we can see, the `timestamp_nanos` field is empty, causing a bad request when attempting to retrieve different possible values for this field.

Environment:

Grafana version: v10.1.2, v10.3.1

**Comment by fmassot** [comment]
thanks for the report @maxnovawind, we are going to investigate this issue.

**Comment by ddelemeny** [comment]
Thank you @maxnovawind, I could reproduce the issue.

There's a race condition between the async construction of a query builder aware of the timestamp field (fetched from index metadata) and the fetching of terms. On refresh, the terms query may be built before the timefield is set, leading to this error.

That's indeed a bug, it should happen only on refresh, you can work around it by navigating to another page.

@fmassot: this can be fixed with a small refactoring of how the datasource handles its querybuilder, PR on the way

**Comment by fmassot** [comment]
@maxnovawind I just published a 0.4.0 beta version.

**Comment by maxnovawind** [comment]
Thanks @fmassot I will try the new version.
